package org.veluka.Vapi.ddbb;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.veluka.Vapi.ddbb.entities.dnd.PjsGear;
import org.veluka.Vapi.ddbb.repository.dnd.PjsGearRepository;

@Controller	// This means that this class is a Controller
public class GestorDatabase {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private PjsGearRepository pjsGearRepository;

	
	
	public Iterable<PjsGear> getAllPjsGear() {
		// This returns a JSON or XML with the users
		return pjsGearRepository.findAll();
	}
}
