package org.veluka.Vapi.ddbb.services.dnd;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.veluka.Vapi.ddbb.entities.dnd.User;
import org.veluka.Vapi.ddbb.repository.dnd.UserRepository;

@Service    // This means that this class is a Controller
@Transactional("dndTransactionManager")
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	public String addNewUser (String name, String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}
	
	public Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
//http://localhost:9992/demo/add?name=First&email=someemail@someemailprovider.com